#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEMPLATE="$REPO_ROOT/Docs/TESTFLIGHT_INTERNAL_EVIDENCE_TEMPLATE.md"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
OUTPUT_PATH="${TESTFLIGHT_EVIDENCE_OUTPUT_PATH:-${TMPDIR:-/tmp}/nightbreath-testflight-evidence-$TIMESTAMP.md}"

fail() {
  printf 'error: %s\n' "$1" >&2
  exit 1
}

[[ -f "$TEMPLATE" ]] || fail "Missing template: ${TEMPLATE#$REPO_ROOT/}"

output_dir="$(dirname "$OUTPUT_PATH")"
mkdir -p "$output_dir"
output_abs="$(cd "$output_dir" && pwd)/$(basename "$OUTPUT_PATH")"

case "$output_abs" in
  "$REPO_ROOT"/*)
    fail "TestFlight evidence must stay private. Choose an output path outside the repository."
    ;;
esac

commit_hash="$(git -C "$REPO_ROOT" rev-parse HEAD)"
branch_name="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)"
status_short="$(git -C "$REPO_ROOT" status --short)"
if [[ -z "$status_short" ]]; then
  status_summary="clean"
else
  status_summary="dirty; review git status before using this as release evidence"
fi

{
  printf '# Private TestFlight Evidence Draft\n\n'
  printf 'Generated by: Tools/Release/prepare_testflight_evidence.sh\n\n'
  printf '| 항목 | 값 |\n'
  printf '| --- | --- |\n'
  printf '| candidate commit hash | %s |\n' "$commit_hash"
  printf '| branch | %s |\n' "$branch_name"
  printf '| generated at | %s |\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '| repository status | %s |\n\n' "$status_summary"
  cat "$TEMPLATE"
} > "$output_abs"

cat <<EOF
TestFlight evidence draft prepared outside the repository.

Output:
  $output_abs

Repository status:
  $status_summary

Do not commit completed TestFlight evidence; keep it in the private QA store.
EOF

